services:
  stats-server:
    build: ./statistics/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-client:
    build: ./statistics/stats-client
    image: stats-client
    container_name: stats-client
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - EWM_SERVER_URL=http://stats-server:9090

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=statistics
      - POSTGRES_USER=statistics
      - POSTGRES_DB=statistics
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10